
import "./globals.css";
import Footer from "app/Components/footer";
import {UserProvider} from "@auth0/nextjs-auth0/client"
import CondicionalNavBar from "app/Components/condicionalNavBar";
import Head from "next/head";


export const metadata = {
  title: "Manager de Biblioteca",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <Head>
        <link rel="icon" href="/images/Creo.png" />
      </Head>
      <html>
        <body>
          <CondicionalNavBar>
            <main>
              <div className="max-w-7xl mx-auto py-6 sm:px-6">{children}</div>
            </main>
          </CondicionalNavBar>
          <Footer/>
        </body>
      </html>
    </UserProvider>
  );
}