
import "./globals.css";
import Footer from "app/Components/footer";
import {UserProvider} from "@auth0/nextjs-auth0/client"
import CondicionalNavBar from "app/Components/condicionalNavBar";
import Head from "next/head";


export const metadata = {
  title: "Manager de Biblioteca",
  description: "Generated by create next app",
  icons: {
    icon: "/images/Creo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html>
        <body className='flex flex-col min-h-screen'>
          <CondicionalNavBar>
            <main>
              <div className="max-w-7xl mx-auto py-6 sm:px-6">{children}</div>
            </main>
          </CondicionalNavBar>
          <Footer/>
        </body>
      </html>
    </UserProvider>
  );
}